# Generated by Django 4.0.3 on 2022-05-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_investments_amount_invested'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='unique_u',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
